"""create user table

Revision ID: 4952be91a9fd
Revises: 
Create Date: 2023-11-10 18:27:56.901295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4952be91a9fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cat', 'image',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cat', 'image',
               existing_type=sa.String(length=100),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    # ### end Alembic commands ###
